#include <Rcpp.h>
using namespace Rcpp;

//' Generate samples drawn from multinomial distirbution.
//'
//' This is a function to generate samples drawn from multinomial distribution fron
//' a given random sequence of LHC.
//'
//' @param n An integer indicating the number of samples.
//' @param size An integer indicating of dimenisions?
//' @param ctime A vector indicating the time instants
//' @param cdf An object of cumulative distribution function
//' @param lhc A numeric matrix generated by LHC.
// [[Rcpp::export]]

NumericMatrix multinomialLHC(int n, int size, NumericVector ctime, Function cdf,
                             NumericMatrix lhc) {
  NumericVector cp = cdf(ctime);
  int m = cp.length();
  NumericMatrix result(m,n);
  for (int i=0; i<n; i++) {
    for (int j=0; j<size; j++) {
      int m = 0;
      while (cp[m] < lhc(i,j)) {
        m++;
      }
      result(m,i) += 1;
    }
  }
  return result;
}

